---
apiVersion: v1
kind: Namespace
metadata:
  name: jwks
---
apiVersion: hana.io/v1
kind: Jwks
metadata:
  name: jwks
  namespace: jwks
spec:
  wellKnownPath: '.well-known/jwks.json'
  version: dev
---
apiVersion: v1
kind: Secret
metadata:
  name: jwks-tls
  namespace: jwks
type: kubernetes.io/tls
data:
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ2VENDQWRFQ0FRRXdEUVlKS29aSWh2Y05B
    UUVMQlFBd1BURUxNQWtHQTFVRUJoTUNSRVV4Q3pBSkJnTlYKQkFnTUFrSlhNUTB3Q3dZRFZRUUtE
    QVJJWVc1aE1SSXdFQVlEVlFRRERBbElZVzVoSUZKdmIzUXdIaGNOTWpFdwpOakV6TVRnME16UTNX
    aGNOTWpJd05qRXpNVGcwTXpRM1dqQTRNUXN3Q1FZRFZRUUdFd0pFUlRFTE1Ba0dBMVVFCkNBd0NR
    bGN4RFRBTEJnTlZCQW9NQkVoaGJtRXhEVEFMQmdOVkJBTU1CRXBYUzFNd2dnRWlNQTBHQ1NxR1NJ
    YjMKRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDcWI4UlREeWxBemRrSC96ZnBObXdIbW1yYWN0
    dktnYUNhYklENQpHc2YzTHZvMHMyb21ZUVd4R0g3eit2N0ZHbldOOVRZRDNrWHQ2RExWQXIyc210
    ek55eGxTYTk1UGZWQ2VteEhBCmUvSGFMaFROSmhuQ0RqL0JBc3VuMEhnWkw4dUJRb0VtZEh6ZWh2
    SjMwaG96RlJPeUxCdXJGWVFQbXRlU2NmQkYKN2VBRHRFdEtzY3RHdG1mTnhhSTY0TWFZQnNKNzUy
    anB4Ujg0Z2hzRUNyNHhtQzJmSy9ZQlZOSmpnOFJuQXplZQp2blJ3MnRlZFQ2NS9HZ1ltVzNyL1Zh
    b2ZESytNVmg1cEJKd0hkL0pLZjdONTA0YjFPaFREcXdYOWh3QXQxamxMCjV5bkVoTndmVWZWdHAz
    ekw2dmdFcTdvei8zWFNwR040R1dMVlREMUxhQ2tVckhNMUFnTUJBQUV3RFFZSktvWkkKaHZjTkFR
    RUxCUUFEZ2dJQkFIZ0lJdWQzMVR4Rml5VGxsRU80Y01kYWd2eWtCbTNKV2FTb2Zud3VDWDdrM1BN
    Qgp4dGRCY3MxVHF0cThmaUpVckVuNWdaYzlRVHVGVEtDMUpTck1SMzUxVnlJc1B4ZE91a1hXOGpq
    ejFuMnhHU0owCmVIbXNvRFBVc2tsMFpWY0tHNkIydkE2M2V5b1A2aGV1S1ZwREl2NWdxTFNUTzFC
    Vk1wSmNhMVBBZ3hqQ2QrOFQKT1BwSUVuSWltVmpJbnZNbTdqZHlDd1p2VDhmemVFZnJQcEE3ZGoz
    eUVxYVl4V2QvSkRzWTVTNEI4U3c3bUZDYQprS05mRFROSzBmSU5ZV2xqUnpoYWQzb0o0ejg2TUdn
    ZEY1SnZlREZhSWx3WVFaVWV6c1ZEai8yNDBCMFBFUU5TCnNKc3N2WmZDdXhjZUZKV1phNS9rZGYv
    NkJKU1AySFYxbjhmaXdBd2lwZzN3aGxPZ3VuR1l2b1RTeFk4ak1DWnkKbE1tRFpndmNkbm44Nkx0
    ZEJYMWtYYmkxV2FIT2Q2czM4dXJSMnloK0hhSTc0V01DN3JaMHhQb1RTRm00YkVacApVMDFxMGht
    QUcwdDE0ZHFNWWlBTWN4amRCeHFvNnhFSUp0M2Z4SitGcU1BZUpMNW1Rd1BLcCtnUUROL0s5UnJE
    CkFndG5tdjE3Y1U0bjYwazhpRHhmQmozc0hWc2p5cW03Qkc5VWltMnJjakpqMjJDVU5KZEJmYWVh
    SXpHQm5uWG4KOS9LVmwwSVFIdVJoS1NmMmxTSTErM1ovUUlteEVBQmk5dVFmYXFiNTc4alRTSFF5
    ZXJqSVJSMlpGb3MrVGJ3dwpITGJITEdNYzZaek9PSmdoZmc3aUQ4N1pXcXBIc2NiaWExTjVoZmYx
    VXphUEpBaTZ5MDFhSkpnN3ptOTIKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: |
    LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBcW0vRVV3OHBR
    TTNaQi84MzZUWnNCNXBxMm5MYnlvR2dtbXlBK1JySDl5NzZOTE5xCkptRUZzUmgrOC9yK3hScDFq
    ZlUyQTk1RjdlZ3kxUUs5ckpyY3pjc1pVbXZlVDMxUW5wc1J3SHZ4Mmk0VXpTWVoKd2c0L3dRTExw
    OUI0R1MvTGdVS0JKblI4M29ieWQ5SWFNeFVUc2l3YnF4V0VENXJYa25Id1JlM2dBN1JMU3JITApS
    clpuemNXaU91REdtQWJDZStkbzZjVWZPSUliQkFxK01aZ3RueXYyQVZUU1k0UEVad00zbnI1MGNO
    clhuVSt1CmZ4b0dKbHQ2LzFXcUh3eXZqRlllYVFTY0IzZnlTbit6ZWRPRzlUb1V3NnNGL1ljQUxk
    WTVTK2NweElUY0gxSDEKYmFkOHkrcjRCS3U2TS85MTBxUmplQmxpMVV3OVMyZ3BGS3h6TlFJREFR
    QUJBb0lCQUZUVHI5alBFTzhxQkx6UQpMNW1vOW5lS1NXaFVCa1J4NCtjMzNiRWR2U3l2ZXVSRDc2
    OE9WdkRmaWtBUVNrRDdmRXFkSXJjbUo1UFRING1aCkJhSWtxWVRiY3N6czF3YWxEajBDWFFGNkx0
    TXlZRFFDcEl0SzREeEdFZXFCL1dRN3Y0T2ovL2VOdnFCYWRjOWgKQ0owbi9sZU5VSEFFRTJoWTNy
    WUtjMVc2b09YMlJCMmJtUEZiRlFWMVdTQjluSzZoeWJFTEZkc1hMNDRNcmMxNApZM01ReWxFZmI2
    Um1UcHI3ZlE4bDEraW4rdEo5Unp2Yzc3UTFIc2pnb0tuY1kzTWpxWVVSbXMwVWpRK05ON3RPCi9p
    U0Q0S2s1d2Z3RTgvUTRkTkpQRFVpUy9rRXFhY3RrT0lnMFZTMlRLTmRHZHpuU0wvdUZ6Q2NxRFFW
    cDB2WmwKQnVsVUNNRUNnWUVBMFpZeU5TV1VidExyWnpxVXlnU0pkeUFHdHZsQmgzbklKTFBwb3N4
    MjRJQmsrN1dzSmsvMQp2TmpEUU4rUlNaSHFRWVZkeWFOaFBvUFR4a3dpa0NzelVOYnhNMXBYZFZt
    VHg3NGYwUEYwNzlpRnBrMCt5anNNCnJoNHdsUHRoVGQxTXpPWCtBRG9FTUgxeUprWVRIRUZsRWJM
    L2Q2TG12WHZ0aVpzTnF1NTJVaTBDZ1lFQTBDNFcKcGczalh0MHF0Q0tTclJIVWFNeTNYN2ZQRHVQ
    aENHVUZOTndRTWsrSW02MGErQUgxT0dZM1Btb3B3KzFkU2dpSApmUWZDdlZKekNXVjU2bEQ0Ulpx
    REtzUDI1TkNBS3N1Y2lyWndpY3JqdDNSbi90aS9tU2x3SG1oWk9mRWFUbS9MCndiNThSOUZsa2x0
    eHozZ1A5a3VFeHMva0JOWlhkblFuK0ZTdXNpa0NnWUVBeDdJQWJMczl6c3FSR1c2cnprQzgKYWhE
    TjFSRng2bytTcjhYczJ2MU9WMkorMVlhb1hHamJqL0JKT2tyS3QvcWI1WW9aYnNLSktYT2FHTnI2
    STd2Rgp6VVMvMVZwQzhzRkRHWktCNWlmcWI0MHk2dDIyOGlHSlYyM1VoRjl3dXl3Y3ZTNTI4ZWhW
    alk0NWNWWmJaeFM0CkpFRVZRUHlxTmVrYXozNDVhNkNDaEpFQ2dZRUF4M2F4V3E5SjRGWFdtYnZh
    ZjVycXd2TUs2OXBJdVFLY1ZaZTkKTWxWNzYwaUxJbVhzeGgzU0lCVEg3N1IyaWZSL0F2VkRKQWZ3
    amNkVzAzVDRLQXNtcGtJU1ZVSm41L3JpSXA3dQpRWFhtUkJBeXVVNythWTZ4bllXM21Gcnd5dlI0
    K1JoaXlTTERIMmpCZ2thOXVFUllQdXRDcjk3Mm9hL2hJMnpOCjgwRG9GV2tDZ1lBZnJiWEtVci9l
    RmJNeVhVUXVNWTZodUhRNGt3cnFWVytaUWY5bXRrcE1xbUFzaGEveENKTkUKWnM5SWs5TDdqOXJa
    OGlsaTlMdGROdnZJRENHQTd2OERIKzM3TWJCdzRPZGR1NTJBWHhzOVFvaUFBNjExcGh0aAo5dElh
    S3JKZ0pIOHpUWHRET0hYR2twaml2ZXJiR09xd3QrQ1FoaEMvNlEzSndpbEs5N2Z2VkE9PQotLS0t
    LUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
  ca.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZXekNDQTBPZ0F3SUJBZ0lVQWJ4VjVXay9M
    eit6WU9RRU1mZXZOc3k4dStvd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1BURUxNQWtHQTFVRUJoTUNS
    RVV4Q3pBSkJnTlZCQWdNQWtKWE1RMHdDd1lEVlFRS0RBUklZVzVoTVJJdwpFQVlEVlFRRERBbElZ
    VzVoSUZKdmIzUXdIaGNOTWpFd05qRXpNVGcwTVRFMFdoY05Nak13TmpFek1UZzBNVEUwCldqQTlN
    UXN3Q1FZRFZRUUdFd0pFUlRFTE1Ba0dBMVVFQ0F3Q1FsY3hEVEFMQmdOVkJBb01CRWhoYm1FeEVq
    QVEKQmdOVkJBTU1DVWhoYm1FZ1VtOXZkRENDQWlJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dJUEFE
    Q0NBZ29DZ2dJQgpBS3pMdWRjYzl2NmdJUXJNdjN6R1ZPZDh0QWtOMGo2NW1mUFFvTVg4R1hEOUxP
    VlhtRWszUDNrY1pmYVgrMkZSCk5relZJTkpvTkF5bGlHNzZCdGUrMmJpOUI3ankwS25RNk90UkNa
    V2pJT3dBT1owSzByQ3lucGNiZU45TEdvWFQKTE9teDlDVGlvd2JWVDlTc1RFQXM0b3N6MmUxZWEz
    ZmxiOVAyL2NqNjJGOWtzZVIyTE96TzZ0OXoxQ1JaOEE0TgpyQm9jb0hGV0tnQ2NsWnFrOThqVGU5
    bDdqL2U3aUtMNXlzL0lmdXFBRkhBMFdkY2pBUDc2djFMQS8ramQ3WHFGCjlyZ1JlMVBIUmQ4b0hv
    dS94bE1IVWZrNlFBUVQ0aFQzUTdKbjI1U1ovWjJPdXoxT2ZPR1d0QW04R05CRDJzVkwKSEt6a25y
    bGIvMXVoWUM3Wnh0eGtHVzRDa0hDazhXdEdNRXEweCsyOEV6aFJXdjRXQ29nZ3NYRUVQaFpQVGls
    UwpvZWxqVG11d0hqMDJQYWFuYTJjNGtmb055NmlHS2Y3ajRROThIUld6eWFHTlRiRXpYZFdZV01q
    Y25UZDkrdGg3CnVDUXBBa05LQ3JDUXJoY1dXanBoeW5LWUNib3dHQWxMRFd1ZEJMbklsUHRDa0wy
    UDFJVVNSQ3BlZE12WnM5NjEKQlRSYzVTeVRZSFRBTEpYbkUzdEI2cm8xeHZ6aHpTNE96NGpxVkRv
    MjBvSGJxdWhXR0RPdG15eUZ1S0J2WTRYagpTbmVwUkNHdVcvc09LcXlSSWMxT2UwNlRycmlqbXk1
    alpFQWt2N3QwQ1N5TlBpWklMcW8rOEZaVitwZUVSaFhjCm94YkpXNndWMXVuUHJTQWtnQkZNSnJp
    V0wycStLNUx0dm9ENFFiQmFxckN0QWdNQkFBR2pVekJSTUIwR0ExVWQKRGdRV0JCUVRNWUxmTUtp
    WitIaVdOVlIvcGRXVDFFQ08zekFmQmdOVkhTTUVHREFXZ0JRVE1ZTGZNS2laK0hpVwpOVlIvcGRX
    VDFFQ08zekFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUNBUUFv
    CmN0bEhZWFYydHFKL0RTVmtKMnk2ZHovazJzSkpVbTZtTUZTTU4vNlhjdHhDektZQlUzOGFWcHBJ
    Zlc1YjV6b3UKRnpYeE16bENXa1JUTGpQTkR0QTJ0dnhYSytXWGV3R0dwTHNUOUo1ZkphWmJWS042
    eW8vQTVzN21oeWdXSjJIZQpTTnlSR09pYkpBaCtSTWxQYmhQUU5YRGQ2NjFtTVBkR0FFWlBySHJn
    SWMrNFBPZjdrVjhNOERiUWxpL09ZZGUvCjdNc212WDFIWm9YWXhnVlhsOHMrWVpoS0duV0RWUjJM
    cVd3dVMxajlJdlJaUlZhVXZDK0J0MDJsSGMwckw0Uy8KQVhxU0ZDTXEyRklNWFdhRDlva3F6NmRK
    WGxnRTZVQXk2RnltaE5mTWducU9OeWdxbGppN3lDVjZqY1dXSTRtTwp1a3c1QmlYdXNNRnhYL08y
    VVJtS0RSN09MbnptbFF3TGd0dXZ0TmEwQ0FmNU9ZWGdNWmJza1Q3RXRnakZnVGxvCkdRdjJHNWpt
    N294enJiZk5GSHhLQjF6SWJhMDZUNTRBbGxqU1RBdU1QRTRobThPQUtoY3ZuaVJLWktqZk9Yd2IK
    cUdyNmVWWTdJZnNrSCtHc3hCZ3JXRHRVR0NlR1U4NkVkc0U1OC9pNzRIc3VkVml4NDhvZVRWakpZ
    RkZQT3BjcgpsWEdzenV0YlQrM1VnSVNjcGRrYlZvMmpWdG9LOXN5TFFTOFozYk9pM3ZNeHczMzJC
    U082K2s1cStVT1ZtbVNECkVaekRydm05U0RYUG0yUW1OWHpRL29tczRxV0lHMHpPY1VFZVVzM3Rm
    T1pjdXRsZnIwcHJya01WdjhoMTNWdVUKYU5vanIvVEpIQWVrd3g5R29VNEcvb3N1NkFlVXNCc3V1
    dmhTSnNaK0ZRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=

