apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: jwks.hana.io
spec:
  group: hana.io
  names:
    singular: jwks
    plural: jwks
    kind: Jwks
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                wellKnownPath:
                  type: string
