---
apiVersion: v1
kind: Service
metadata:
  name: jwks
  labels:
    app: jwks
spec:
  selector:
    app: jwks
  ports:
    - port: 80
      protocol: TCP
      targetPort: 7777
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jwks
  labels:
    app: jwks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jwks
  template:
    metadata:
      labels:
        app: jwks
    spec:
      containers:
        - name: jwks
          ports:
            - containerPort: 7777
              name: http
              protocol: TCP
          image: kostkams/hana-jwks:VERSION
          imagePullPolicy: Always
          env:
            - name: WELL_KNOWN_PATH
              value: ''
            - name: JWKS
              valueFrom:
                secretKeyRef:
                  key: jwks
                  name: jwks
                  optional: false
            - name: PORT
              value: '7777'

