---
apiVersion: v1
kind: Service
metadata:
  name: jwks
  labels:
    app: jwks
spec:
  selector:
    app: jwks
  ports:
    - port: 80
      protocol: TCP
      targetPort: 7777
      name: http
    - port: 443
      protocol: TCP
      targetPort: 7443
      name: https
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jwks
  labels:
    app: jwks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jwks
  template:
    metadata:
      labels:
        app: jwks
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
    spec:
      containers:
        - name: jwks
          ports:
            - containerPort: 7777
              name: http
              protocol: TCP
            - containerPort: 7443
              name: https
              protocol: TCP
          image: kostkams/hana-jwks:VERSION
          imagePullPolicy: Always
          env:
            - name: WELL_KNOWN_PATH
              value: ''
            - name: JWKS
              valueFrom:
                secretKeyRef:
                  key: jwks
                  name: jwks
                  optional: false
            - name: PORT_PUBLIC
              value: '7777'
            - name: PORT_INTERNAL
              value: '7443'
            - name: JWKS_TLS_KEY
              valueFrom:
                secretKeyRef:
                  key: tls.key
                  name: jwks-tls
            - name: JWKS_TLS_CRT
              valueFrom:
                secretKeyRef:
                  key: tls.crt
                  name: jwks-tls
            - name: CA_TLS_CRT
              valueFrom:
                secretKeyRef:
                  key: ca.crt
                  name: jwks-tls
          readinessProbe:
            httpGet:
              path: /health
              port: 7777
            initialDelaySeconds: 30
            periodSeconds: 3
          livenessProbe:
            httpGet:
              port: 7777
              path: /live
            initialDelaySeconds: 30
            periodSeconds: 3
          startupProbe:
            httpGet:
              port: 7777
              path: /ready
            initialDelaySeconds: 5
            periodSeconds: 3

---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: jwks-mapping
spec:
  prefix: ''
  service: jwks-sidecar-proxy
  resolver: consul-dc1
  tls: ambassador-consul
  load_balancer:
    policy: round_robin
